---
title: "Read_Recruitment_Submission_SAR11_Metabolism"
author: "Sarah Tucker"
date: "8/6/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
setwd("/Users/sarahtucker/Documents/Metagenome_manuscript/SAR11_Isolates_Metagenomic_Analyses/working_in_R")


library(reshape2)
library(tidyverse)

```


#########Ia3V

```{bash}
###no need for tis
cd /Users/sarahtucker/Documents/Metagenome_manuscript/SAR11_Isolates_Metagenomic_Analyses/working_in_R/
mkdir Ia3V_read_recruit
for file in $(<Ia3V_SCG_filenames.txt); do file=$(echo "$file" | tr -d '\r'); cp "$file" ./Ia3V_read_recruit/; done

```


```{bash}
IFS=$'\n'; for line in `cat sublineage_names.txt | tail -n +2`; do
  bin=$(echo "$line" | awk '{print $1}');
  sublineage=$(echo "$line" | awk '{print $2}' | tr -d '\r');      
  dest=~/Documents/Metagenome_manuscript/SAR11_Isolates_Metagenomic_Analyses/working_in_R/aloha_depth_read_recruit/$sublineage;
  mkdir -p "$dest";
  cp ~/Documents/Metagenome_manuscript/SAR11_Isolates_Metagenomic_Analyses/SAR11-KbyT-Alohadepth-newgenomes-SUMMARY/bin_by_bin/$bin/$bin-gene_non_outlier_coverages.txt "$dest/";
done
```




#########Ia3V
```{r}
sample_SCG_v2=read.csv("help2.csv", header=TRUE, row.names=1)

pangenome_Ia3V=read.delim("v2-just-Ia3V-Aloha_KByT-depth-PAN_gene_clusters_summary copy.txt")
pangenome_Ia3V_SCG=subset(pangenome_Ia3V, bin_name=="Ia3V_single_copy")

SumsIa4II_Ia41483=sample_SCG_v2
SumsIa41483=sample_SCG_v2
SumsIa4rs39=sample_SCG_v2
SumsIa4II=sample_SCG_v2
SumsIa3III=sample_SCG_v2
SumsIa3II=sample_SCG_v2
SumsIa3VI=sample_SCG_v2
SumsIa3V=sample_SCG_v2

fileNames <- list.files(path="/Users/sarahtucker/Documents/Metagenome_manuscript/SAR11_Isolates_Metagenomic_Analyses/working_in_R/aloha_depth_read_recruit/Ia.3.V/", pattern="*.txt", full.names=FALSE, recursive=FALSE)
fileNames

for (fileName in fileNames) {
  # read original data:
  sample <- read.delim(paste0("/Users/sarahtucker/Documents/Metagenome_manuscript/SAR11_Isolates_Metagenomic_Analyses/working_in_R/aloha_depth_read_recruit/Ia.3.V/",fileName))
  # create new data based on contents of original file:
  
sample_SCG=inner_join(pangenome_Ia3V_SCG,sample, by="gene_callers_id" )
sample_SCG=column_to_rownames(sample_SCG, "gene_callers_id")
sample_SCG_v2=sample_SCG[,25:131]
SumsIa3V[nrow(SumsIa3V) + 1,] <- colSums(sample_SCG_v2)
hh=dim(SumsIa3V)
row.names(SumsIa3V)[hh[1]] <- gsub("gene_non_outlier_coverages.txt", "Sum",fileName) 

sample_SCG_v2[nrow(sample_SCG_v2) + 1,] <- colSums(sample_SCG_v2)
gg=dim(sample_SCG_v2)
row.names(sample_SCG_v2)[gg[1]] <- gsub("gene_non_outlier_coverages.txt", "Sum",fileName)

print(sample_SCG_v2)
csvfile<-paste0("SCG_",fileName,".csv")
name<-paste0("SCG_",fileName)
as.data.frame(assign(name, sample_SCG_v2))
write.csv(sample_SCG_v2,csvfile)
}

SumsIa3V_v2=SumsIa3V[-1,]

write.csv(SumsIa3V_v2, "SumsIa3V_v2.csv")

```

#########Ia3VI

```{r}
pangenome_Ia3VI=read.delim("just_Ia3VI-no1602-Aloha_KByT-depth-PAN_gene_clusters_summary copy.txt")
unique(pangenome_Ia3VI$bin_name)
unique(pangenome_Ia3VI$bin_name)
pangenome_Ia3VI_SCG=subset(pangenome_Ia3VI, bin_name=="Ia3VI_single_copy")



fileNames <- list.files(path="/Users/sarahtucker/Documents/Metagenome_manuscript/SAR11_Isolates_Metagenomic_Analyses/working_in_R/aloha_depth_read_recruit/Ia.3.VI/", pattern="*.txt", full.names=FALSE, recursive=FALSE)
fileNames

for (fileName in fileNames) {
  # read original data:
  sample <- read.delim(paste0("/Users/sarahtucker/Documents/Metagenome_manuscript/SAR11_Isolates_Metagenomic_Analyses/working_in_R/aloha_depth_read_recruit/Ia.3.VI/",fileName))
  # create new data based on contents of original file:
  
sample_SCG=inner_join(pangenome_Ia3VI_SCG,sample, by="gene_callers_id" )
sample_SCG=column_to_rownames(sample_SCG, "gene_callers_id")
sample_SCG_v2=sample_SCG[,25:131]
SumsIa3VI[nrow(SumsIa3VI) + 1,] <- colSums(sample_SCG_v2)
hh=dim(SumsIa3VI)
row.names(SumsIa3VI)[hh[1]] <- gsub("gene_non_outlier_coverages.txt", "Sum",fileName) 

sample_SCG_v2[nrow(sample_SCG_v2) + 1,] <- colSums(sample_SCG_v2)
gg=dim(sample_SCG_v2)
row.names(sample_SCG_v2)[gg[1]] <- gsub("gene_non_outlier_coverages.txt", "Sum",fileName)

print(sample_SCG_v2)
csvfile<-paste0("SCG_",fileName,".csv")
name<-paste0("SCG_",fileName)
as.data.frame(assign(name, sample_SCG_v2))
write.csv(sample_SCG_v2,csvfile)
}

SumsIa3VI_v2=SumsIa3VI[-1,]

write.csv(SumsIa3VI_v2, "SumsIa3VI.csv")

```


#########Ia3II
```{r}
pangenome_Ia3II=read.delim("just-Ia3II-Aloha_KByT-depth-PAN_gene_clusters_summary copy.txt")
unique(pangenome_Ia3II$bin_name)
unique(pangenome_Ia3II$genome_name)
pangenome_Ia3II_SCG=subset(pangenome_Ia3II, bin_name=="Ia3II_single_copy")



fileNames <- list.files(path="/Users/sarahtucker/Documents/Metagenome_manuscript/SAR11_Isolates_Metagenomic_Analyses/working_in_R/aloha_depth_read_recruit/Ia.3.II/", pattern="*.txt", full.names=FALSE, recursive=FALSE)
fileNames

for (fileName in fileNames) {
  # read original data:
  sample <- read.delim(paste0("/Users/sarahtucker/Documents/Metagenome_manuscript/SAR11_Isolates_Metagenomic_Analyses/working_in_R/aloha_depth_read_recruit/Ia.3.II/",fileName))
  # create new data based on contents of original file:
  
sample_SCG=inner_join(pangenome_Ia3II_SCG,sample, by="gene_callers_id" )
sample_SCG=column_to_rownames(sample_SCG, "gene_callers_id")
sample_SCG_v2=sample_SCG[,25:131]
SumsIa3II[nrow(SumsIa3II) + 1,] <- colSums(sample_SCG_v2)
hh=dim(SumsIa3II)
row.names(SumsIa3II)[hh[1]] <- gsub("gene_non_outlier_coverages.txt", "Sum",fileName) 

sample_SCG_v2[nrow(sample_SCG_v2) + 1,] <- colSums(sample_SCG_v2)
gg=dim(sample_SCG_v2)
row.names(sample_SCG_v2)[gg[1]] <- gsub("gene_non_outlier_coverages.txt", "Sum",fileName)

print(sample_SCG_v2)
csvfile<-paste0("SCG_",fileName,".csv")
name<-paste0("SCG_",fileName)
as.data.frame(assign(name, sample_SCG_v2))
write.csv(sample_SCG_v2,csvfile)
}

SumsIa3II_v2=SumsIa3II[-1,]
write.csv(SumsIa3II_v2, "SumsIa3II.csv")


```

#########Ia3III
```{r}
pangenome_Ia3III=read.delim("just-Ia3III-Aloha_KByT-depth-PAN_gene_clusters_summary copy.txt")
unique(pangenome_Ia3III$bin_name)
unique(pangenome_Ia3III$genome_name)
pangenome_Ia3III_SCG=subset(pangenome_Ia3III, bin_name=="Ia3III_single_copy")



fileNames <- list.files(path="/Users/sarahtucker/Documents/Metagenome_manuscript/SAR11_Isolates_Metagenomic_Analyses/working_in_R/aloha_depth_read_recruit/Ia.3.III/", pattern="*.txt", full.names=FALSE, recursive=FALSE)
fileNames

for (fileName in fileNames) {
  # read original data:
  sample <- read.delim(paste0("/Users/sarahtucker/Documents/Metagenome_manuscript/SAR11_Isolates_Metagenomic_Analyses/working_in_R/aloha_depth_read_recruit/Ia.3.III/",fileName))
  # create new data based on contents of original file:
  
sample_SCG=inner_join(pangenome_Ia3III_SCG,sample, by="gene_callers_id" )
sample_SCG=column_to_rownames(sample_SCG, "gene_callers_id")
sample_SCG_v2=sample_SCG[,25:131]
SumsIa3III[nrow(SumsIa3III) + 1,] <- colSums(sample_SCG_v2)
hh=dim(SumsIa3III)
row.names(SumsIa3III)[hh[1]] <- gsub("gene_non_outlier_coverages.txt", "Sum",fileName) 

sample_SCG_v2[nrow(sample_SCG_v2) + 1,] <- colSums(sample_SCG_v2)
gg=dim(sample_SCG_v2)
row.names(sample_SCG_v2)[gg[1]] <- gsub("gene_non_outlier_coverages.txt", "Sum",fileName)

print(sample_SCG_v2)
csvfile<-paste0("SCG_",fileName,".csv")
name<-paste0("SCG_",fileName)
as.data.frame(assign(name, sample_SCG_v2))
write.csv(sample_SCG_v2,csvfile)
}

SumsIa3III_v2=SumsIa3III[-1,]
write.csv(SumsIa3III_v2, "SumsIa3III.csv")

```


##Ia.4.II
```{r}

pangenome_Ia4II=read.delim("just-Ia4II-Aloha_KByT-depth-PAN_gene_clusters_summary copy.txt")
unique(pangenome_Ia4II$bin_name)
unique(pangenome_Ia4II$genome_name)
pangenome_Ia4II_SCG=subset(pangenome_Ia4II, bin_name=="Ia4II_single_copy")



fileNames <- list.files(path="/Users/sarahtucker/Documents/Metagenome_manuscript/SAR11_Isolates_Metagenomic_Analyses/working_in_R/aloha_depth_read_recruit/Ia.4.II/", pattern="*.txt", full.names=FALSE, recursive=FALSE)
fileNames

for (fileName in fileNames) {
  # read original data:
  sample <- read.delim(paste0("/Users/sarahtucker/Documents/Metagenome_manuscript/SAR11_Isolates_Metagenomic_Analyses/working_in_R/aloha_depth_read_recruit/Ia.4.II/",fileName))
  # create new data based on contents of original file:
  
sample_SCG=inner_join(pangenome_Ia4II_SCG,sample, by="gene_callers_id" )
sample_SCG=column_to_rownames(sample_SCG, "gene_callers_id")
sample_SCG_v2=sample_SCG[,25:131]
SumsIa4II[nrow(SumsIa4II) + 1,] <- colSums(sample_SCG_v2)
hh=dim(SumsIa4II)
row.names(SumsIa4II)[hh[1]] <- gsub("gene_non_outlier_coverages.txt", "Sum",fileName) 

sample_SCG_v2[nrow(sample_SCG_v2) + 1,] <- colSums(sample_SCG_v2)
gg=dim(sample_SCG_v2)
row.names(sample_SCG_v2)[gg[1]] <- gsub("gene_non_outlier_coverages.txt", "Sum",fileName)

print(sample_SCG_v2)
csvfile<-paste0("SCG_",fileName,".csv")
name<-paste0("SCG_",fileName)
as.data.frame(assign(name, sample_SCG_v2))
write.csv(sample_SCG_v2,csvfile)
}

SumsIa4II_v2=SumsIa4II[-1,]
write.csv(SumsIa4II_v2, "SumsIa4II.csv")

```

##Ia4.rs39
```{r}

pangenome_Ia4rs39=read.delim("just-Ia4rs39-Aloha_KByT-depth-PAN_gene_clusters_summary copy.txt")
unique(pangenome_Ia4rs39$bin_name)
unique(pangenome_Ia4rs39$genome_name)
pangenome_Ia4rs39_SCG=subset(pangenome_Ia4rs39, bin_name=="Ia4rs39_single_copy")



fileNames <- list.files(path="/Users/sarahtucker/Documents/Metagenome_manuscript/SAR11_Isolates_Metagenomic_Analyses/working_in_R/aloha_depth_read_recruit/Ia.4.rs39/", pattern="*.txt", full.names=FALSE, recursive=FALSE)
fileNames

for (fileName in fileNames) {
  # read original data:
  sample <- read.delim(paste0("/Users/sarahtucker/Documents/Metagenome_manuscript/SAR11_Isolates_Metagenomic_Analyses/working_in_R/aloha_depth_read_recruit/Ia.4.rs39/",fileName))
  # create new data based on contents of original file:
  
sample_SCG=inner_join(pangenome_Ia4rs39_SCG,sample, by="gene_callers_id" )
sample_SCG=column_to_rownames(sample_SCG, "gene_callers_id")
sample_SCG_v2=sample_SCG[,25:131]
SumsIa4rs39[nrow(SumsIa4rs39) + 1,] <- colSums(sample_SCG_v2)
hh=dim(SumsIa4rs39)
row.names(SumsIa4rs39)[hh[1]] <- gsub("gene_non_outlier_coverages.txt", "Sum",fileName) 

sample_SCG_v2[nrow(sample_SCG_v2) + 1,] <- colSums(sample_SCG_v2)
gg=dim(sample_SCG_v2)
row.names(sample_SCG_v2)[gg[1]] <- gsub("gene_non_outlier_coverages.txt", "Sum",fileName)

print(sample_SCG_v2)
csvfile<-paste0("SCG_",fileName,".csv")
name<-paste0("SCG_",fileName)
as.data.frame(assign(name, sample_SCG_v2))
write.csv(sample_SCG_v2,csvfile)
}

SumsIa4rs39_v2=SumsIa4rs39[-1,]
write.csv(SumsIa4rs39_v2, "SumsIa4rs39.csv")

```


```{r}

pangenome_Ia4II_Ia41483=read.delim("just-Ia4II-Ia41483-Aloha_KByT-depth-PAN_gene_clusters_summary copy.txt")
unique(pangenome_Ia4II_Ia41483$bin_name)
unique(pangenome_Ia4II_Ia41483$genome_name)
pangenome_Ia4II_Ia41483=subset(pangenome_Ia4II_Ia41483, genome_name=="HIMB1483")
pangenome_Ia4II_Ia41483_SCG=subset(pangenome_Ia4II_Ia41483, bin_name=="Ia4II_1a41483_single_copy")



#SumsIa4II_Ia41483=SumsIa4II_Ia41483[1,]

fileNames <- list.files(path="/Users/sarahtucker/Documents/Metagenome_manuscript/SAR11_Isolates_Metagenomic_Analyses/working_in_R/aloha_depth_read_recruit/Ia.4.1483/", pattern="*.txt", full.names=FALSE, recursive=FALSE)
fileNames

for (fileName in fileNames) {
  # read original data:
  sample <- read.delim(paste0("/Users/sarahtucker/Documents/Metagenome_manuscript/SAR11_Isolates_Metagenomic_Analyses/working_in_R/aloha_depth_read_recruit/Ia.4.1483/",fileName))
  # create new data based on contents of original file:
  
sample_SCG=inner_join(pangenome_Ia4II_Ia41483_SCG,sample, by="gene_callers_id" )
sample_SCG=column_to_rownames(sample_SCG, "gene_callers_id")
sample_SCG_v2=sample_SCG[,25:131]
SumsIa4II_Ia41483[nrow(SumsIa4II_Ia41483) + 1,] <- colSums(sample_SCG_v2)
hh=dim(SumsIa4II_Ia41483)
row.names(SumsIa4II_Ia41483)[hh[1]] <- gsub("gene_non_outlier_coverages.txt", "Sum",fileName) 

sample_SCG_v2[nrow(sample_SCG_v2) + 1,] <- colSums(sample_SCG_v2)
gg=dim(sample_SCG_v2)
row.names(sample_SCG_v2)[gg[1]] <- gsub("gene_non_outlier_coverages.txt", "Sum",fileName)

print(sample_SCG_v2)
csvfile<-paste0("SCG_",fileName,".csv")
name<-paste0("SCG_",fileName)
as.data.frame(assign(name, sample_SCG_v2))
write.csv(sample_SCG_v2,csvfile)
}



SumsIa4II_Ia41483_v2=SumsIa4II_Ia41483[-1,]


write.csv(SumsIa4II_Ia41483_v2, "SumsIa4II_Ia41483.csv")

```


```{r}

sample_SCG_v2=read.csv("help2.csv", header=TRUE, row.names=1)


all_clades=sample_SCG_v2

aggIa3II=SumsIa3II_v2
all_clades[nrow(all_clades) + 1,] <- colSums(aggIa3II)
hh=dim(all_clades)
row.names(all_clades)[hh[1]] <- "Ia3II" 

aggIa3V=SumsIa3V_v2
all_clades[nrow(all_clades) + 1,] <- colSums(aggIa3V)
hh=dim(all_clades)
row.names(all_clades)[hh[1]] <- "Ia3V" 

aggIa3VI=SumsIa3VI_v2
all_clades[nrow(all_clades) + 1,] <- colSums(aggIa3VI)
hh=dim(all_clades)
row.names(all_clades)[hh[1]] <- "Ia3VI" 


aggIa3III=SumsIa3III_v2
all_clades[nrow(all_clades) + 1,] <- colSums(aggIa3III)
hh=dim(all_clades)
row.names(all_clades)[hh[1]] <- "Ia3III" 


aggIa4II=SumsIa4II_v2
all_clades[nrow(all_clades) + 1,] <- colSums(aggIa4II)
hh=dim(all_clades)
row.names(all_clades)[hh[1]] <- "Ia4II" 

aggIa4rs39=SumsIa4rs39_v2
all_clades[nrow(all_clades) + 1,] <- colSums(aggIa4rs39)
hh=dim(all_clades)
row.names(all_clades)[hh[1]] <- "Ia4rs39" 

aggIa41483=SumsIa4II_Ia41483_v2
all_clades[nrow(all_clades) + 1,] <- colSums(aggIa41483)
hh=dim(all_clades)
row.names(all_clades)[hh[1]] <- "Ia41483" 


all_clades2=all_clades[-1,]
write.csv(all_clades2, "all_clades_SCG_read_recruit_KByT_Aloha.csv")

#total recruitment of SAR11??- does that mean to the total of this or to the total of all SAR11 in this group

okay=read.csv("dectection_accounted_SCGread_recruit.csv", row.names = 1)


freqs2 <- apply(okay, 2, function(i) i/sum(i))

freqs3=freqs2*100
freqs3=as.data.frame(freqs3)

write.csv(freqs3, "SAR11depthaloha_relative_read_recruit_SCG_detection_acc.csv")
```


